# Generated by Django 2.2.6 on 2019-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('template_file', models.FileField(upload_to='')),
            ],
        ),
    ]
